package models

import (
	"encoding/json"

	"github.com/dracocity/draco-payment-bridge-core/internal/types"
)

type CreatePaymentLinkRequest struct {
	Amount          string `json:"amount"`                     // amount (e.g. "1000")
	Currency        string `json:"currency"`                   // currency (e.g. "USD")
	ReceiveCurrency string `json:"receive_currency,omitempty"` // receive currency (e.g. "BTC")

	OrderID       string `json:"order_id"`
	Description   string `json:"description,omitempty"` // description
	Items         []Item `json:"items,omitempty"`
	CustomerEmail string `json:"customer_email"`

	WebhookURL string `json:"webhook_url,omitempty"` // ipn/notification/callback url
	SuccessURL string `json:"success_url,omitempty"` // redirect url on success
	CancelURL  string `json:"cancel_url,omitempty"`  // redirect url on cancel/close

	ProviderPayload json.RawMessage `json:"provider_payload,omitempty"`
}

type CreatePaymentLinkResponse struct {
	InvoiceID string `json:"invoice_id"` // provider invoice id

	Amount          string `json:"amount"`                     // provider returned amount
	Currency        string `json:"currency"`                   // provider returned currency
	ReceiveCurrency string `json:"receive_currency,omitempty"` // provider returned receive currency

	OrderID     string `json:"order_id"`
	Description string `json:"description,omitempty"` // description

	CheckoutURL string `json:"checkout_url"` // checkout page url
	// QRCodeURL  *string `json:"qr_code_url,omitempty"` // optional
	WebhookURL string `json:"webhook_url,omitempty"` // ipn/notification/callback url
	SuccessURL string `json:"success_url,omitempty"` // redirect url on success
	CancelURL  string `json:"cancel_url,omitempty"`  // redirect url on cancel/close

	ExpiresAt *int64 `json:"expires_at,omitempty"` // unix milli
	CreatedAt int64  `json:"created_at"`           // unix milli
	UpdatedAt int64  `json:"updated_at"`           // unix milli

	Raw any `json:"raw,omitempty"`
}

type CreatePaymentRequest struct {
	InvoiceID string `json:"invoice_id"` // provider invoice id

	ReceiveCurrency string `json:"receive_currency"` // receive currency (e.g. "BTC")

	Description   string `json:"description,omitempty"` // description
	CustomerEmail string `json:"customer_email"`

	ProviderPayload json.RawMessage `json:"provider_payload"`

	// TODO
	// OrderID    string  `json:"order_id"`
	// WebhookURL *string `json:"webhook_url"`
}

type CreatePaymentResponse struct {
	Status    types.PaymentStatus `json:"status"`     // Current payment status in the payment lifecycle
	PaymentID string              `json:"payment_id"` // Unique payment identifier generated by the provider

	Amount          string `json:"amount"`
	Currency        string `json:"currency"`
	ReceiveAmount   string `json:"receive_amount"`   // receive amount
	ReceiveCurrency string `json:"receive_currency"` // receive currency

	OrderID     string `json:"order_id"`              // Merchant's order identifier associated with this payment
	Description string `json:"description,omitempty"` // description

	ExpiresAt int64 `json:"expires_At"` // Expiration timestamp after which payment is no longer valid
	CreatedAt int64 `json:"created_at"` // Timestamp when the payment was created
	UpdatedAt int64 `json:"updated_at"` // Last provider update timestamp (unix milli)

	Raw any `json:"raw,omitempty"`
}

// GetPaymentResponse represents the current information of a payment.
type GetPaymentResponse struct {
	Status types.PaymentStatus `json:"status"` // normalized payment status

	Amount          string `json:"amount"`                     // amount
	Currency        string `json:"currency"`                   // currency
	ReceiveAmount   string `json:"receive_amount,omitempty"`   // receive amount
	ReceiveCurrency string `json:"receive_currency,omitempty"` // receive currency
	EstimatedAmount string `json:"estimated_amount,omitempty"` // estimated amount

	PaymentID   string `json:"payment_id"`            // Unique payment identifier generated by the provider
	OrderID     string `json:"order_id"`              // Merchant's order identifier associated with this payment
	Description string `json:"description,omitempty"` // description

	CreatedAt int64 `json:"created_at"` // unix milli
	UpdatedAt int64 `json:"updated_at"` // unix milli
	Raw       any   `json:"raw,omitempty"`
}

// CreateRefundRequest is the unified refund request payload.
type CreateRefundRequest struct {
	PaymentID string  `json:"payment_id"`
	Amount    float64 `json:"amount"`
	Reason    string  `json:"reason"`
}

// CreateRefundResponse represents the unified refund response.
type CreateRefundResponse struct {
	Success    bool   `json:"success"`
	RefundID   string `json:"refund_id"`
	PaymentID  string `json:"payment_id"`
	Amount     string `json:"amount"`
	Currency   string `json:"currency"`
	Status     string `json:"status"`
	RefundType string `json:"refund_type"`
}

// WebhookResult is returned after a provider webhook is processed.
type WebhookResult struct {
	Accepted bool   `json:"accepted"`
	Message  string `json:"message"`
}
