package models

import (
	"encoding/json"

	"github.com/dracocity/draco-payment-bridge-core/internal/types"
)

type CreatePaymentLinkRequest struct {
	Amount          string `json:"amount"`                     // amount (e.g. "1000")
	Currency        string `json:"currency"`                   // currency (e.g. "USD")
	ReceiveCurrency string `json:"receive_currency,omitempty"` // receive currency (e.g. "BTC")

	OrderID     string `json:"order_id"`
	Description string `json:"description,omitempty"` // description

	WebhookURL string `json:"webhook_url,omitempty"` // ipn/notification/callback url
	SuccessURL string `json:"success_url,omitempty"` // redirect url on success
	CancelURL  string `json:"cancel_url,omitempty"`  // redirect url on cancel/close

	ProviderPayload json.RawMessage `json:"provider_payload,omitempty"`
}

type CreatePaymentLinkResponse struct {
	// ===== Basic Identification =====
	Status    *types.PaymentStatus `json:"status,omitempty"`
	InvoiceID string               `json:"invoice_id"` // provider invoice id
	OrderID   string               `json:"order_id"`
	// ===== Payment Amount Information =====
	Amount   string `json:"amount,omitempty"`   // provider returned amount
	Currency string `json:"currency,omitempty"` // provider returned currency
	// CryptoAmount   string `json:"crypto_amount,omitempty"`   // provider returned crypto amount
	// CryptoCurrency string `json:"crypto_currency,omitempty"` // provider returned crypto currency
	// ===== Payment Receiving Information =====
	CheckoutURL string `json:"checkout_url"` // checkout page url
	// QRCodeURL  *string `json:"qr_code_url,omitempty"` // optional
	// ===== Time Information =====
	// ExpiresAt *int64 `json:"expires_at,omitempty"` // unix milli
	CreatedAt int64 `json:"created_at"` // unix milli
	UpdatedAt int64 `json:"updated_at"` // unix milli
	// ===== Provider Raw Response =====
	Raw any `json:"raw,omitempty"`
}

type CreatePaymentRequest struct {
	InvoiceID string `json:"invoice_id"` // provider invoice id

	// TODO
	OrderID         string          `json:"order_id"`
	Description     *string         `json:"description"`
	WebhookURL      *string         `json:"webhook_url"`
	ProviderPayload json.RawMessage `json:"provider_payload"`

	Amount   string `json:"amount"` // decimal
	Currency string `json:"currency"`
	Crypto   string `json:"crypto"`
}

type CreatePaymentResponse struct {
	// ===== Basic Identification =====
	Status    types.PaymentStatus `json:"status"`     // Current payment status in the payment lifecycle
	PaymentID string              `json:"payment_id"` // Unique payment identifier generated by the provider
	OrderID   string              `json:"order_id"`   // Merchant's order identifier associated with this payment
	// ===== Payment Amount Information =====
	Currency     string `json:"currency"`      // Cryptocurrency symbol (e.g., BTC, ETH, USDT)
	Amount       string `json:"amount"`        // Exact crypto amount the customer must send (string for precision, no float)
	FiatCurrency string `json:"fiat_currency"` // Fiat currency code (e.g., USD, KRW)
	FiatAmount   string `json:"fiat_amount"`   // Fiat currency amount equivalent at creation time
	Network      string `json:"network"`       // Blockchain network used (e.g., ERC20, TRC20, Bitcoin)
	ExchangeRate string `json:"exchange_rate"` // Exchange rate applied when the payment was created
	// ===== Payment Receiving Information =====
	DepositAddress string  `json:"deposit_address"` // Blockchain address where the customer must send funds
	Memo           *string `json:"memo,omitempty"`  // Optional memo/tag required for certain networks (e.g., XRP, BNB)
	// ===== Confirmation Tracking =====
	ConfirmationsRequired int `json:"confirmations_required"` // Number of blockchain confirmations required to mark payment as completed
	Confirmations         int `json:"confirmations"`          // Current number of confirmations received
	// ===== Amount Tracking =====
	PaidAmount      string `json:"paid_amount"`      // Total crypto amount received so far
	RemainingAmount string `json:"remaining_amount"` // Remaining amount to be paid (if partial payment)
	OverpaidAmount  string `json:"overpaid_amount"`  // Amount exceeding required payment (if overpaid)
	// ===== Time Information =====
	ExpiresAt int64 `json:"expires_At"` // Expiration timestamp after which payment is no longer valid
	CreatedAt int64 `json:"created_at"` // Timestamp when the payment was created
	UpdatedAt int64 `json:"updated_at"` // Last provider update timestamp (unix milli)
	// ===== Security & Traceability =====
	Signature string `json:"signature"`  // Cryptographic signature to verify response integrity
	RequestID string `json:"request_id"` // Unique request identifier for API tracing and debugging
	// ===== Provider Raw Response =====
	Raw any `json:"raw,omitempty"`
}

// GetPaymentResponse represents the current information of a payment.
type GetPaymentResponse struct {
	// ===== Basic Identification =====
	Status    types.PaymentStatus `json:"status"`     // Current payment status in the payment lifecycle
	PaymentID string              `json:"payment_id"` // Unique payment identifier generated by the provider
	OrderID   string              `json:"order_id"`   // Merchant's order identifier associated with this payment
	// ===== Payment Amount Information =====
	Currency     string `json:"currency"`      // Cryptocurrency symbol (e.g., BTC, ETH, USDT)
	Amount       string `json:"amount"`        // Expected crypto amount for this payment
	FiatCurrency string `json:"fiat_currency"` // Fiat currency code (e.g., USD, KRW)
	FiatAmount   string `json:"fiat_amount"`   // Fiat currency amount at payment creation time
	Network      string `json:"network"`       // Blockchain network used (e.g., ERC20, TRC20, Bitcoin)
	ExchangeRate string `json:"exchange_rate"` // Effective exchange rate at payment creation or settlement
	// ===== Payment Receiving Information =====
	DepositAddress  string  `json:"deposit_address"`  // Address where funds should be sent
	Memo            *string `json:"memo,omitempty"`   // Optional memo/tag for networks requiring destination tags
	TransactionHash string  `json:"transaction_hash"` // Primary transaction hash observed for this payment
	// ===== Confirmation Tracking =====
	ConfirmationsRequired int `json:"confirmations_required"` // Required confirmations to finalize payment
	Confirmations         int `json:"confirmations"`          // Current observed confirmations
	// ===== Amount Tracking =====
	PaidAmount      string `json:"paid_amount"`      // Total amount received so far
	RemainingAmount string `json:"remaining_amount"` // Amount still required to complete the payment
	OverpaidAmount  string `json:"overpaid_amount"`  // Amount received above expected amount
	// ===== Time Information =====
	ExpiresAt int64 `json:"expires_at"` // Payment expiration timestamp (unix milli)
	CreatedAt int64 `json:"created_at"` // Payment creation timestamp (unix milli)
	UpdatedAt int64 `json:"updated_at"` // Last provider update timestamp (unix milli)
	// ===== Provider Raw Response =====
	Raw any `json:"raw,omitempty"`
}

// RefundRequest is the unified refund request payload.
type RefundRequest struct {
	Provider  string  `json:"provider"`
	PaymentID string  `json:"payment_id"`
	Amount    float64 `json:"amount"`
	Reason    string  `json:"reason"`
}

// RefundResponse represents the unified refund response.
type RefundResponse struct {
	Success    bool   `json:"success"`
	RefundID   string `json:"refund_id"`
	PaymentID  string `json:"payment_id"`
	Amount     string `json:"amount"`
	Currency   string `json:"currency"`
	Status     string `json:"status"`
	RefundType string `json:"refund_type"`
}

// WebhookResult is returned after a provider webhook is processed.
type WebhookResult struct {
	Accepted bool   `json:"accepted"`
	Message  string `json:"message"`
}
