package response

import (
	"strconv"
	"strings"

	"github.com/dracocity/draco-payment-bridge-core/internal/consts"
	"github.com/dracocity/draco-payment-bridge-core/internal/models"
	"github.com/dracocity/draco-payment-bridge-core/internal/types"
	"github.com/dracocity/draco-payment-bridge-core/pkg/utils"
)

func BuildCreatePaymentLink(resp CreateInvoice) (*models.CreatePaymentLinkResponse, error) {
	createdAt := utils.ToUnixMilli(resp.CreatedAt)
	updatedAt := utils.ToUnixMilli(resp.UpdatedAt)
	if updatedAt == 0 {
		updatedAt = createdAt
	}
	return &models.CreatePaymentLinkResponse{
		InvoiceID:       resp.ID,
		Amount:          resp.PriceAmount.String(),
		Currency:        strings.ToUpper(resp.PriceCurrency),
		ReceiveCurrency: strings.ToUpper(utils.PtrValueOrDefault(resp.PayCurrency, "")),
		OrderID:         utils.PtrValueOrDefault(resp.OrderID, ""),
		CheckoutURL:     resp.InvoiceURL,
		WebhookURL:      utils.PtrValueOrDefault(resp.IPNCallbackURL, ""),
		SuccessURL:      utils.PtrValueOrDefault(resp.SuccessURL, ""),
		CancelURL:       utils.PtrValueOrDefault(resp.CancelURL, ""),
		CreatedAt:       createdAt,
		UpdatedAt:       updatedAt,
		Raw:             resp,
	}, nil
}

func BuildGetPayment(resp GetPayment) (*models.GetPaymentResponse, error) {
	createdAt := utils.ToUnixMilli(resp.CreatedAt)
	updatedAt := utils.ToUnixMilli(resp.UpdatedAt)
	if updatedAt == 0 {
		updatedAt = createdAt
	}
	return &models.GetPaymentResponse{
		Status:          normalizeNowPaymentsStatus(resp.PaymentStatus),
		Amount:          resp.PriceAmount.String(),
		Currency:        strings.ToUpper(resp.PriceCurrency),
		ReceiveAmount:   resp.ActuallyPaid.String(),
		ReceiveCurrency: strings.ToUpper(resp.PayCurrency),
		EstimatedAmount: resp.PayAmount.String(),
		PaymentID:       strconv.FormatInt(resp.PaymentID, 10),
		OrderID:         utils.PtrValueOrDefault(resp.OrderID, ""),
		Description:     utils.PtrValueOrDefault(resp.OrderDescription, ""),
		CreatedAt:       createdAt,
		UpdatedAt:       updatedAt,
		Raw:             resp,
	}, nil
}

func normalizeNowPaymentsStatus(status string) types.PaymentStatus {
	switch strings.ToLower(strings.TrimSpace(status)) {
	case "new":
		return consts.StatusCreated
	case "waiting":
		return consts.StatusPending
	case "confirming", "sending":
		return consts.StatusConfirming
	case "partially_paid":
		return consts.StatusPartiallyPaid
	case "finished", "confirmed":
		return consts.StatusCompleted
	case "failed", "refunded":
		return consts.StatusFailed
	case "expired":
		return consts.StatusExpired
	default:
		normalized := strings.ToUpper(strings.TrimSpace(status))
		if normalized == "" {
			return consts.StatusPending
		}
		return types.PaymentStatus(normalized)
	}
}

/*
Status types.PaymentStatus `json:"status"` // normalized payment status

	Amount          string `json:"amount"`                     // amount
	Currency        string `json:"currency"`                   // currency
	ReceiveAmount   string `json:"receive_amount,omitempty"`   // receive amount
	ReceiveCurrency string `json:"receive_currency,omitempty"` // receive currency

	PaymentID   string `json:"payment_id"`            // Unique payment identifier generated by the provider
	OrderID     string `json:"order_id"`              // Merchant's order identifier associated with this payment
	Description string `json:"description,omitempty"` // description

	CreatedAt int64 `json:"created_at"` // unix milli
	Raw       any   `json:"raw,omitempty"`
*/
